In [11]:
def trie_intervalle(tab, ig, id):
    """
    :entrée-sortie tab: tableau de float
    :entrée ig: int
    :entrée id: int
    :pré-cond: 0 ≤ ig ≤ id < len(tab)
    :post-cond: tab- (tab tel qu'il est passé en entrée)
                contient les mêmes valeurs entre ig et id
                que tab+ (tab tel qu'il est en sortie),
                mais tab+ est trié entre ig et id
    """
    

# Tri par sélection

Principe: on cherche le minimum, et on le permute avec la pemière case. Puis on recommence entre à partir de la 2e case, puis la 3e, et ainsi de suite.

In [12]:
## tri par sélection

def min_intervalle(tab, ig, id):
    """
    :entrée tab: tableau de float
    :entrée ig: int
    :entrée id: int
    :pré-cond: 0 ≤ ig ≤ id < len(tab)
    :sortie imin: int
    :post-cond: tab[imin] est la plus petite valeur dans tab
                entre ig et id
    """
    imin = ig
    i = ig+1
    while i <= id:
        if tab[i] < tab[imin]:
            imin = i
        i = i+1
    return imin
    
    
def trie_intervalle(tab, ig, id):
    
    while ig < id:
        imin = min_intervalle(tab, ig, id)
        tmp = tab[ig]
        tab[ig] = tab[imin]
        tab[imin] = tmp
        ig = ig+1
        

In [14]:
from numpy import array
a = array([7,2,3,5,1,5])
trie_intervalle(a, 0, len(a)-1)
print(a)

[1 2 3 5 5 7]


## Version récursive

In [8]:
## tri par sélection

def min_intervalle(tab, ig, id):
    if ig == id:
        imin = ig
    else:
        imin = min_intervalle(tab, ig+1, id)
        if tab[ig] < tab[imin]:
            imin = ig
    return imin
    
def trie_intervalle(tab, ig, id):
    if ig == id:
        pass # rien à faire
    else:
        imin = min_intervalle(tab, ig, id)
        tmp = tab[ig]
        tab[ig] = tab[imin]
        tab[imin] = tmp
        
        trie_intervalle(tab, ig+1, id)

In [15]:
a = array([7,2,3,5,1,5])
trie_intervalle(a, 0, len(a)-1)
print(a)

[1 2 3 5 5 7]


# Tri par insertion

Principe: on considère le sous-tableau composé des 2 premières cases; il est presque trié, il n'y a qu'à insérer (en la décalant) la 2e valeur à la bonne position. Après cette manipulation, le sous-tableau composé des 3 premières cases est presque trié, il n'y a plus qu'à insérer la 3e valeur à la bonne position. Après cela, le sous-tableau composé des 4 premières cases est presque trié, et ainsi de suite. Par propagation, on arrive à trier la totalité du tableau.

In [17]:
def insere_d(tab, ig, id):
    """
    :entrée-sortie tab: tableau de float
    :entrée ig: int
    :entrée id: int
    :pré-cond: 0 ≤ ig < id < len(tab)
               tab est trié entre ig et id-1
    :post-cond: tab- (tab tel qu'il est passé en entrée)
                contient les mêmes valeurs entre ig et id
                que tab+ (tab tel qu'il est en sortie),
                mais tab+ est trié entre ig et id
    """
    i = id
    while i > ig  and  tab[i-1] > tab[i]:
        tmp = tab[i]
        tab[i-1] = tab[i]
        tab[i] = tmp
        i = i-1
        
def insere_d(tab, ig, id):
    # un peu plus économique
    val = tab[id]
    i = id  # position du "trou" laissé par tab[id]
    while i > ig  and  tab[i-1] > val:
        tab[i] = tab[i-1]
        i = i-1
    tab[i] = val

def trie_intervalle(tab, ig, id):
    i = ig+1
    while i <= id:
        insere_d(tab, ig, i)
        i = i+1

In [19]:
a = array([7,2,3,5,1,5])
trie_intervalle(a, 0, len(a)-1)
print(a)

[1 2 3 5 5 7]


## Version récursive

In [22]:
def insere_d(tab, ig, id):
    if ig == id:
        pass # rien à faire
    else:
        if tab[id-1] > tab[id]:
            tmp = tab[id-1]
            tab[id-1] = tab[id]
            tab[id] = tmp
        insere_d(tab, ig, id-1)

def trie_intervalle(tab, ig, id):
    if ig == id:
        pass # rien à faire
    else:
        trie_intervalle(tab, ig, id-1)
        insere_d(tab, ig, id)

In [24]:
a = array([7,2,3,5,1,5])
trie_intervalle(a, 0, len(a)-1)
print(a)

[1 2 3 5 5 7]


# Tri binaire (ou tri rapide - *quicksort*)

Principe: on choisit une valeur pivot au hasard, et on partitionne le tableau de sorte que toutes les valeurs inférieure au pivot soient situées à sa gauche (mais dans n'importe quel ordre), et que toutes les valeurs supérieures au pivot soient situées à sa droite (dans n'importe quel ordre).
On appele ensuite récursivement ``trie_intervalle`` sur ces deux sous-tableaux.

In [30]:
def partitionne(tab, ig, id, pivot):
    """
    :entrée-sortie tab: tableau de float
    :entrée ig: int
    :entrée id: int
    :entrée pivot: float
    :sortie ip: int
    :pré-cond: 0 ≤ ig ≤ id < len(tab)
    :post-cond: les valeurs de tab sont permutées de sorte que
                toutes les valeures inférieures ou égales au pivot soient à gauche,
                et que toutes les valeurs supérieures soient à droite
                ip est l'indice de la dernière valeur inférieure ou égale au pivot
    """
    while ig <= id:
        if tab[ig] <= pivot:
            ig = ig+1
        else:
            if tab[id] > pivot:
                id = id-1
            else:
                tmp = tab[ig]
                tab[ig] = tab[id]
                tab[id] = tmp
                ig = ig+1
                id = id-1
    ip = id
    return ip

def trie_intervalle(tab, ig, id):
    if ig >= id:
        pass # rien à faire
    else:
        # n'importe quelle valeur peut faire office de pivot
        pivot = tab[ig] # on prend donc la première
        # on sépare le tableau en deux "tas" (plus petit / plus grand que le pivot)
        ip = partitionne(tab, ig+1, id, pivot)
        # on permute le pivot pour qu'il soit entre les deux "tas"
        tmp = tab[ig]
        tab[ig] = tab[ip]
        tab[ip] = tmp
        # on trie récursivement les deux "tas"
        trie_intervalle(tab, ig, ip-1)
        trie_intervalle(tab, ip+1, id)

In [31]:
a = array([7,2,3,5,1,5])
trie_intervalle(a, 0, len(a)-1)
print(a)

[1 2 3 5 5 7]
