In [54]:
from numpy import array, empty

tab = array([10,20,30,40,50])
print(tab)

[10 20 30 40 50]


# Opérations disponibles sur les tableaux

In [59]:
# un tableau a une longueur
print(len(tab))

5


In [60]:
# on peut accéder à chaque élément individuellement
print(tab[1])
# (comme pour les chaînes, les éléments sont numérotés à partir de 0)

20


In [71]:
# on peut modifier un élément d'un tableau
tab[1] = 99
print(tab)

[10 99 30 40 50]


# Construction d'un tableau

In [73]:
# en extension
tab1 = array([12.3, 45.6, 78.9])
print(tab1)

[ 12.3  45.6  78.9]


In [75]:
# tableau "vide" (en fait: non initialisé)
tab2 = empty(20, int)
print(tab2)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


# Le *même* tableau peut être pointé par plusieurs variables

In [64]:
a = array([10,20,30])
b = a
a[1] = 99
print(b)

[10 99 30]


Cela peut sembler contradictoire avec le fonctionnement d'autres types de données, comme les entiers.

In [66]:
a = 42
b = a
a = a+1
print(b)

42


Cette apparente "incohérence" vient du fait que les lignes 3 des 2 programmes ci-dessus sont très différentes. Dans un cas, on change un élément du tableau sans changer l'identité du tableau pointé par les variables *a* et *b*. Dans le second cas, on change réaffecte la variable *a*, ce qui n'a pas d'incidence sur la variable *b*.

L'exemple ci-dessus avec des entiers correspond donc plutôt à l'exemble suivant avec des tableaux.

In [70]:
a = array([10,20,30])
b = a
a = array([10,99,30])
print(b)

[10 20 30]


# Exercices

In [28]:
def zeros(n):
    """
    :entrée n: int
    :pré-cond: n > 0
    :sortie tab: tableau d'int
    :post-cond: len(tab) == n, pour tout i, tab[i] == 0
    """
    tab = empty(n, int)
    i = 0
    while i < n:
        tab[i] = 0
        i = i+1
    return tab

print(zeros(10))

[0 0 0 0 0 0 0 0 0 0]


In [30]:
def sequence(n):
    """
    :entrée n: int
    :pré-cond: n > 0
    :sortie tab: tableau d'int
    :post-cond: len(tab) == n, pour tout i, tab[i] == i
    """
    tab = empty(n, int)
    i = 0
    while i < n:
        tab[i] = i
        i = i+1
    return tab

print(sequence(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [35]:
def répétition(n, éléments):
    """
    :entrée n: int
    :entrée éléments: tableau d'int
    :pré-cond: n > 0
    :sortie tab: tableau d'int
    :post-cond: len(tab) == n, et pour tout i
                tab[i] = éléments[i % len(éléments)]
    """
    tab = empty(n, int)
    i = 0
    j = 0
    while i < n:
        tab[i] = éléments[j]
        i = i+1
        j = j+1
        if j >= len(éléments):
            j = 0
    return tab

def répétition(n, éléments):
    """
    :entrée n: int
    :entrée éléments: tableau d'int
    :pré-cond: n > 0
    :sortie tab: tableau d'int
    :post-cond: len(tab) == n, et pour tout i
                tab[i] = éléments[i % len(éléments)]
    """
    tab = empty(n, int)
    i = 0
    while i < n:
        tab[i] = éléments[i % len(éléments)]
        i = i+1
    return tab

print(répétition(10, array([10,20,30])))

[10 20 30 10 20 30 10 20 30 10]


In [38]:
def concat_tableaux(tab1, tab2):
    """
    :entrée tab1: tableau d'int
    :entrée tab2: tableau d'int
    :pré-cond: -
    :sortie tabc: tableau d'int
    :post-cond: tabc est la concaténation de tab1 et tab2, c.à.d.
                len(tabc) = len(tab1) + len(tab2)
                tabc[i] = tab1[i] pour 0 ≤ i < len(tab1)
                tabc[i] = tab2[i-len(tab1)] pour len(tab1) ≤ i < len(tabc)
    """
    tabc = empty(len(tab1)+len(tab2),int)
    i = 0
    while i < len(tab1):
        tabc[i] = tab1[i]
        i = i + 1
    while i < len(tab1) + len(tab2):
        tabc[i] = tab2[i - len(tab1)]
        i = i + 1
    return tabc
print(concat_tableaux(array([10,20,30]), array([2,4,6,8,10])))

[10 20 30  2  4  6  8 10]


# La boucle `for`

Syntaxe: 

  for <variable> in <tableau>:
      <corps de la boucle>
      
La variable prend successivement toutes les valeurs contenues du tableau.

NB: cela fonctionne aussi avec une chaîne.

In [77]:
for c in "hello":
    print(c)

h
e
l
l
o


In [79]:
for i in sequence(10):
    print(i)

0
1
2
3
4
5
6
7
8
9
